### ISSUE TITLE
ModuleNotFoundError: No module named 'weights.model_path'

### ISSUE THREAD

**Issue by LandryK** [artest08/LateTemporalModeling3DCNN#14]
Hi, 
Thank you for your great work!
I'm currently trying to run the training for the  the baseline code using "two_strream_bert2.py" 
I get the following error: 
ModuleNotFoundError: No module named 'weights.model_path'

The weights folder contains 5 files which I downloaded as per the instructions. However, the "model_path.py" file is apparently missing from this folder. Therefore, the following import fails: 
"from weights.model_path import rgb_3d_model_path_selection".

Please could you point me to where I could get this file? or is there an alternative to fixing this issue?

Thanks

**Comment by dpdls2840** [comment]
Hi. This problem can be solved when you edit "from weights.model_path" into "from utils.model_path".

**Comment by ghost** [comment]
> Hi,
> Thank you for your great work!
> I'm currently trying to run the training for the the baseline code using "two_strream_bert2.py"
> I get the following error:
> ModuleNotFoundError: No module named 'weights.model_path'
> 
> The weights folder contains 5 files which I downloaded as per the instructions. However, the "model_path.py" file is apparently missing from this folder. Therefore, the following import fails:
> "from weights.model_path import rgb_3d_model_path_selection".
> 
> Please could you point me to where I could get this file? or is there an alternative to fixing this issue?
> 
> Thanks

Hi. This problem can be solved when you edit "from weights.model_path" into "from utils.model_path".
