### ISSUE TITLE
roi-align==0.0.2 cannot be installed

### ISSUE THREAD

**Issue by kenzoukun** [artest08/LateTemporalModeling3DCNN#2]
An error occurred when I execute the following command：conda env create -f LateTemporalModeling3D.yml

ERROR: Could not find a version that satisfies the requirement roi-align==0.0.2 (from -r /data/LateTemporalModeling3DCNN/condaenv.u7mj_9s2.requirements.txt (line 58)) (from versions: none)
ERROR: No matching distribution found for roi-align==0.0.2 (from -r /data/LateTemporalModeling3DCNN/condaenv.u7mj_9s2.requirements.txt (line 58))

CondaValueError: pip returned an error

Thanks for your help!

**Comment by artest08** [comment]
Hello, thank you for your feedback. 

According to my trials it is not a necessary package. I deleted it from the environment, and it seems that everything is fine. Can you delete it from the yml file and send your feedback again about this topic? Then I will also update the yml file in the repository.

Thanks in advance
