### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement fvcore==0.1

### ISSUE THREAD

**Issue by AfrinaVT** [artest08/LateTemporalModeling3DCNN#5]
when I try to create the environment this error shows up
ERROR: No matching distribution found for fvcore==0.1 (from -r /home/afrina/LateTemporalModeling3DCNN-master/condaenv.63nxe8d0.requirements.txt (line 13))

**Comment by wjtan99** [comment]
@AfrinaVT I encountered this same problem.  You do not need to follow exactly the yml file.  You can try running the code, every time you have a package not installed, simply use pip install package.  I got it running this way.  Try it.

**Comment by AfrinaVT** [comment]
when you ran did it say module not found weights.model_path?

**Comment by wjtan99** [comment]
@AfrinaVT Yes, but the weights file can be downloaded in a link given in the page: 

"Later, please download the necessary files from the link, and copy them into the main directory. https://1drv.ms/u/s!AqKP51Rjkz1Gaifd54VbdRBn6qM?e=7OxYLa"

**Comment by AfrinaVT** [comment]
I downloaded the files still was showing the error. Then I did not set the model path beforehand. In my understanding, it should not affect the training as I am training from beginning

**Comment by EddieMG** [comment]
> I downloaded the files still was showing the error. Then I did not set the model path beforehand. In my understanding, it should not affect the training as I am training from beginning

There's an issue adressing this specific error. Seems like it is a typo instead of weights.model_path it should be utils.model_path.
https://github.com/artest08/LateTemporalModeling3DCNN/issues/12
https://github.com/artest08/LateTemporalModeling3DCNN/issues/8

**Comment by fcakyon** [comment]
@AfrinaVT @wjtan99 fvcore error should be fixed on the master branch. Thanks for your attention!
